name: Rain CI
on: [push]

jobs:
  rainix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [rainix-rs-test, rainix-rs-artifacts]
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - run: nix run .#rainix-rs-prelude

      - name: Run ${{ matrix.task }}
        run: nix run .#${{ matrix.task }}